# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: hydra-maester

before:
  hooks:
    - "go mod download"

builds:
  - flags:
      - -a
    binary: manager
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - 386
      - arm64
    goos:
      - linux
      - darwin

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc

dockers:
  - image_templates:
      - "oryd/hydra-maester:v{{ .Major }}"
      - "oryd/hydra-maester:v{{ .Major }}.{{ .Minor }}"
      - "oryd/hydra-maester:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "oryd/hydra-maester:{{ .Env.DOCKER_SHORT_TAG }}"
      - "oryd/hydra-maester:latest"

release:
  prerelease: auto
  name_template: "{{.Env.RELEASE_NAME}}"
